NewMap2_MapScripts::
	.byte 0


bulbasaur_pokeball::
# 4 "data/maps/NewMap2/scripts.pory"
	lock
# 5 "data/maps/NewMap2/scripts.pory"
	showmonpic SPECIES_BULBASAUR, 10, 3
# 6 "data/maps/NewMap2/scripts.pory"
	delay 3
# 7 "data/maps/NewMap2/scripts.pory"
	hidemonpic
# 8 "data/maps/NewMap2/scripts.pory"
	msgbox bulbasaur_pokeball_Text_0
# 9 "data/maps/NewMap2/scripts.pory"
	release
	end


charmander_pokeball::
# 14 "data/maps/NewMap2/scripts.pory"
	lock
# 15 "data/maps/NewMap2/scripts.pory"
	showmonpic SPECIES_CHARMANDER, 10, 3
# 16 "data/maps/NewMap2/scripts.pory"
	delay 3
# 17 "data/maps/NewMap2/scripts.pory"
	hidemonpic
# 18 "data/maps/NewMap2/scripts.pory"
	msgbox charmander_pokeball_Text_0
# 19 "data/maps/NewMap2/scripts.pory"
	release
	end


squirtle_pokeball::
# 24 "data/maps/NewMap2/scripts.pory"
	lock
# 25 "data/maps/NewMap2/scripts.pory"
	showmonpic SPECIES_SQUIRTLE, 10, 3
# 26 "data/maps/NewMap2/scripts.pory"
	delay 3
# 27 "data/maps/NewMap2/scripts.pory"
	hidemonpic
# 28 "data/maps/NewMap2/scripts.pory"
	msgbox squirtle_pokeball_Text_0
# 29 "data/maps/NewMap2/scripts.pory"
	release
	end


abra_pokeball::
# 34 "data/maps/NewMap2/scripts.pory"
	lock
# 35 "data/maps/NewMap2/scripts.pory"
	showmonpic SPECIES_ABRA, 10, 3
# 36 "data/maps/NewMap2/scripts.pory"
	delay 3
# 37 "data/maps/NewMap2/scripts.pory"
	hidemonpic
# 38 "data/maps/NewMap2/scripts.pory"
	msgbox abra_pokeball_Text_0
# 39 "data/maps/NewMap2/scripts.pory"
	release
	end


pidgey_pokeball::
# 44 "data/maps/NewMap2/scripts.pory"
	lock
# 45 "data/maps/NewMap2/scripts.pory"
	showmonpic SPECIES_PIDGEY, 10, 3
# 46 "data/maps/NewMap2/scripts.pory"
	delay 3
# 47 "data/maps/NewMap2/scripts.pory"
	hidemonpic
# 48 "data/maps/NewMap2/scripts.pory"
	msgbox pidgey_pokeball_Text_0
# 49 "data/maps/NewMap2/scripts.pory"
	release
	end


ekans_pokeball::
# 54 "data/maps/NewMap2/scripts.pory"
	lock
# 55 "data/maps/NewMap2/scripts.pory"
	showmonpic SPECIES_EKANS, 10, 3
# 56 "data/maps/NewMap2/scripts.pory"
	delay 3
# 57 "data/maps/NewMap2/scripts.pory"
	hidemonpic
# 58 "data/maps/NewMap2/scripts.pory"
	msgbox ekans_pokeball_Text_0
# 59 "data/maps/NewMap2/scripts.pory"
	release
	end


eevee_pokeball::
# 64 "data/maps/NewMap2/scripts.pory"
	lock
# 65 "data/maps/NewMap2/scripts.pory"
	showmonpic SPECIES_EEVEE, 10, 3
# 66 "data/maps/NewMap2/scripts.pory"
	delay 3
# 67 "data/maps/NewMap2/scripts.pory"
	hidemonpic
# 68 "data/maps/NewMap2/scripts.pory"
	msgbox eevee_pokeball_Text_0
# 69 "data/maps/NewMap2/scripts.pory"
	release
	end


caterpie_pokeball::
# 74 "data/maps/NewMap2/scripts.pory"
	lock
# 75 "data/maps/NewMap2/scripts.pory"
	showmonpic SPECIES_CATERPIE, 10, 3
# 76 "data/maps/NewMap2/scripts.pory"
	delay 3
# 77 "data/maps/NewMap2/scripts.pory"
	hidemonpic
# 78 "data/maps/NewMap2/scripts.pory"
	msgbox caterpie_pokeball_Text_0
# 79 "data/maps/NewMap2/scripts.pory"
	release
	end


rattatta_pokeball::
# 84 "data/maps/NewMap2/scripts.pory"
	lock
# 85 "data/maps/NewMap2/scripts.pory"
	showmonpic SPECIES_RATTATA, 10, 3
# 86 "data/maps/NewMap2/scripts.pory"
	delay 3
# 87 "data/maps/NewMap2/scripts.pory"
	hidemonpic
# 88 "data/maps/NewMap2/scripts.pory"
	msgbox rattatta_pokeball_Text_0
# 89 "data/maps/NewMap2/scripts.pory"
	release
	end


sandshrew_pokeball::
# 94 "data/maps/NewMap2/scripts.pory"
	lock
# 95 "data/maps/NewMap2/scripts.pory"
	showmonpic SPECIES_SANDSHREW, 10, 3
# 96 "data/maps/NewMap2/scripts.pory"
	delay 3
# 97 "data/maps/NewMap2/scripts.pory"
	hidemonpic
# 98 "data/maps/NewMap2/scripts.pory"
	msgbox sandshrew_pokeball_Text_0
# 99 "data/maps/NewMap2/scripts.pory"
	release
	end


machop_pokeball::
# 103 "data/maps/NewMap2/scripts.pory"
	lock
# 104 "data/maps/NewMap2/scripts.pory"
	showmonpic SPECIES_MACHOP, 10, 3
# 105 "data/maps/NewMap2/scripts.pory"
	delay 3
# 106 "data/maps/NewMap2/scripts.pory"
	hidemonpic
# 107 "data/maps/NewMap2/scripts.pory"
	msgbox machop_pokeball_Text_0
# 108 "data/maps/NewMap2/scripts.pory"
	release
	end


growlithe_pokeball::
# 112 "data/maps/NewMap2/scripts.pory"
	lock
# 113 "data/maps/NewMap2/scripts.pory"
	showmonpic SPECIES_GROWLITHE, 10, 3
# 114 "data/maps/NewMap2/scripts.pory"
	delay 3
# 115 "data/maps/NewMap2/scripts.pory"
	hidemonpic
# 116 "data/maps/NewMap2/scripts.pory"
	msgbox growlithe_pokeball_Text_0
# 117 "data/maps/NewMap2/scripts.pory"
	release
	end


bulbasaur_pokeball_Text_0:
# 8 "data/maps/NewMap2/scripts.pory"
	.string "Oh no! Someone already took bulbasaur!$"

charmander_pokeball_Text_0:
# 18 "data/maps/NewMap2/scripts.pory"
	.string "Oh no! Someone already took\n"
	.string "charmander!$"

squirtle_pokeball_Text_0:
# 28 "data/maps/NewMap2/scripts.pory"
	.string "Oh no! Someone already took squirtle!$"

abra_pokeball_Text_0:
# 38 "data/maps/NewMap2/scripts.pory"
	.string "Oh no! Someone already took abra!$"

pidgey_pokeball_Text_0:
# 48 "data/maps/NewMap2/scripts.pory"
	.string "Oh no! Someone already took pidgey!$"

ekans_pokeball_Text_0:
# 58 "data/maps/NewMap2/scripts.pory"
	.string "Oh no! Someone already took ekans!$"

eevee_pokeball_Text_0:
# 68 "data/maps/NewMap2/scripts.pory"
	.string "Oh no! Someone already took eevee!$"

caterpie_pokeball_Text_0:
# 78 "data/maps/NewMap2/scripts.pory"
	.string "Oh no! Someone already took caterpie!$"

rattatta_pokeball_Text_0:
# 88 "data/maps/NewMap2/scripts.pory"
	.string "Oh no! Someone already took ratatta!$"

sandshrew_pokeball_Text_0:
# 98 "data/maps/NewMap2/scripts.pory"
	.string "Oh no! Someone already took sandshrew!$"

machop_pokeball_Text_0:
# 107 "data/maps/NewMap2/scripts.pory"
	.string "Oh no! Someone already took machop!$"

growlithe_pokeball_Text_0:
# 116 "data/maps/NewMap2/scripts.pory"
	.string "Oh no! Someone already took growlithe!$"
